name: paradoc
channels:
  - conda-forge
  - krande
dependencies:
  - pandoc 3.1.2
  - pandoc-crossref 0.3.16
  - pypandoc 1.12
  - python-docx
  - docxcompose
  - typer
  - numpy
  - pandas
  - openpyxl
  - tabulate
  - svgwrite
  - pytexit
  - nomkl
  - pytest
  - miktex 23.5