name: paradoc
channels:
  - conda-forge
  - krande
dependencies:
  - pandoc
  - pandoc-crossref
  - pypandoc
  - python-docx
  - docxcompose
  - typer
  - numpy
  - pandas
  - openpyxl
  - tabulate
  - svgwrite
  - pytexit
  - nomkl
  - pytest