"""OpenDocument Text (.odt) export, straight from pandoc.

The same route as the PDF export -- the built markdown joined into one document, figure and table
captions numbered by pandoc-crossref -- written with pandoc's own ODT writer. No office suite is
needed to produce it, and LibreOffice, Word and Google Docs all open it.
"""

import pathlib

import pypandoc

from paradoc import OneDoc
from paradoc.io.pdf.exporter import prepare_images
from paradoc.utils import copy_figures_to_dist

#: Text width of pandoc's default ODT page: US Letter less its 1 in margins.
TEXT_WIDTH_IN = 6.5

_IMAGE_WIDTH_FILTER = """-- Generated by paradoc for this ODT export: fit wide images to the text block.
-- The ODT writer sizes an image from its pixels and DPI, and a PNG without DPI metadata counts as
-- 72 dpi -- a 640 px render comes out 8.9 in wide and runs off the page. Set any image wider than
-- the text block to its width (the height follows); leave smaller images and explicit sizes alone.
local TEXT_WIDTH_IN = {text_width}

function Image(img)
  if img.attributes.width or img.attributes.height then return nil end
  local ok, _, contents = pcall(pandoc.mediabag.fetch, img.src)
  if not ok or not contents then return nil end
  local ok_size, size = pcall(pandoc.image.size, contents)
  if not ok_size or not size or not size.width then return nil end
  local dpi = (size.dpi_horz and size.dpi_horz > 0) and size.dpi_horz or 72
  if size.width / dpi > TEXT_WIDTH_IN then
    -- An absolute width, not "100%": pandoc keeps the 640 pt svg:width beside a relative one,
    -- and not every ODT reader honours the relative size.
    img.attributes.width = TEXT_WIDTH_IN .. "in"
    return img
  end
end
"""


def image_width_filter(out_dir: pathlib.Path) -> pathlib.Path:
    """Write the Lua filter that fits wide images to the page and return its path."""
    path = out_dir / "paradoc-odt-images.lua"
    path.write_text(_IMAGE_WIDTH_FILTER.format(text_width=TEXT_WIDTH_IN), encoding="utf-8")
    return path


class OdtExporter:
    def __init__(self, one_doc: OneDoc):
        self.one_doc = one_doc

    def export(self, dest_file: pathlib.Path):
        one = self.one_doc
        out_dir = dest_file.parent

        copy_figures_to_dist(one, out_dir)

        def built(md) -> str:
            return prepare_images(md.read_built_file(), md.build_file.parent, out_dir)

        # No appendix marker: the PDF's is a raw LaTeX \appendix, which the ODT writer drops.
        combined_str = "\n\n".join(built(md) for md in [*one.md_files_main, *one.md_files_app])

        pypandoc.convert_text(
            combined_str,
            one.FORMATS.ODT,
            outputfile=str(dest_file),
            format="markdown",
            extra_args=[
                "-M2GB",
                "+RTS",
                "-K64m",
                "-RTS",
                f"--resource-path={out_dir}",
                f"--metadata-file={one.metadata_file}",
            ],
            filters=["pandoc-crossref", str(image_width_filter(out_dir))],
        )
        print(f'Successfully exported ODT to "{dest_file}"')
