{% set name = "paradoc" %}
{% set data = load_setup_py_data() %}

package:
  name: "{{ name|lower }}"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
#  preserve_egg_dir: True

requirements:
  build:
    - python
  run:
    - python
    - pandoc
    - pandoc-crossref
    - pypandoc
    - python-docx
    - docxcompose
    - numpy
    - pandas
    - openpyxl
    - tabulate
    - svgwrite
    - pytexit
    - nomkl
test:
  source_files:
    - tests
    - files
  requires:
    - pytest
    - pytest-cov
  commands:
    - cd tests
    - pytest

about:
  home: https://github.com/krande/paradoc
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: "A Python library for Parametric Documentation"


extra:
  recipe-maintainers:
    - Krande