{% set name = "paradoc" %}
{% set data = load_setup_py_data() %}
{% set version = load_file_data('pyproject.toml')["project"]["version"] %}

package:
  name: "{{ name|lower }}"
  version: {{ version}}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps -vv
  entry_points:
    - paradoc=paradoc.cli_app:app

requirements:
  host:
    - python
  run:
    - python
    - pandoc
    - pandoc-crossref
    - pypandoc
    - python-docx
    - docxcompose
    - numpy
    - pandas
    - openpyxl
    - tabulate
    - svgwrite
    - pytexit
    - typer
    - nomkl
test:
  source_files:
    - tests
    - files
  requires:
    - pytest
    - pytest-cov
  commands:
    - cd tests
    - pytest

about:
  home: https://github.com/krande/paradoc
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: "A Python library for Parametric Documentation"


extra:
  recipe-maintainers:
    - Krande