version: '3.8'

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - gitea-data:/data

  fastapi:
    build: ..
    image: paradoc/git-doc
    container_name: git-doc

    ports:
      - "8000:8000"
    depends_on:
      - gitea

volumes:
  gitea-data:
