name: ci-paradoc-main

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'conda/**'
      - '.github/workflows/ci.yml'
    branches:
    - main

jobs:
  activate:
    if: |
      github.repository == 'Krande/paradoc' &&
      !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - run: echo ok go
  lint:
    needs: activate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Install lint packages
      run: pip install isort flake8 black
    - name: Lint with isort
      run: isort --check .
    - name: Lint with flake8
      run: flake8 .
    - name: Lint with black
      run: black --config pyproject.toml --check .
  build:
    needs: lint
    name: ${{ matrix.platform.name }}-${{ matrix.pyver.name }}
    runs-on: ${{ matrix.platform.distver }}
    strategy:
      fail-fast: false
      matrix:
        pyver: [ { name: py38, distver: '3.8' }, { name: py39, distver: '3.9' } ]
        platform: [
          { name: Windows, distver: windows-latest },
          { name: Linux, distver: ubuntu-latest },
          { name: macOS, distver: macos-latest }
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2  # https://github.com/conda-incubator/setup-miniconda
        with:
          activate-environment: anaconda-client-env
          python-version: ${{ matrix.pyver.distver }}
          environment-file: conda/environment.yml

      - name: build, test and upload conda package
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        shell: bash -l {0}
        run: |
          conda-build -c krande -c conda-forge conda --python=${{ matrix.pyver.distver }} --token=$ANACONDA_TOKEN --user krande --override-channels

      - name: build and test conda package
        shell: bash -l {0}
        run: |
          conda-build -c krande -c conda-forge conda --python=${{ matrix.pyver.distver }} --override-channels


