name: ci-paradoc-main

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'conda/**'
      - '.github/workflows/ci.yml'
    branches:
    - main
  pull_request:
    paths-ignore:
      - setup.py
    branches:
      - main
#  schedule:
#    - cron: '0 0 * * 7'  # every sunday at midnight

jobs:
  activate:
    if: |
      github.repository == 'Krande/paradoc' &&
      !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - run: echo ok go
  lint:
    needs: activate
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: actions/checkout@v3
      - name: Install lint packages
        run: pip install isort ruff black
      - name: Lint with black
        run: black --config pyproject.toml --check .
      - name: Lint with isort
        run: isort --check .
      - name: Lint with ruff
        run: ruff .
  build:
    needs: activate
    name: ${{ matrix.platform.name }}-${{ matrix.pyver.name }}
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    env:
      CONDALABEL: krande
      CONDALABEL2: ''
    strategy:
      fail-fast: false
      matrix:
        pyver: [
          { name: py39, distver: '3.9' },
          { name: py310, distver: '3.10' },
          { name: py311, distver: '3.11' }
        ]
        platform: [
          { name: Windows, distver: windows-latest },
          { name: Linux, distver: ubuntu-latest },
          { name: macOS, distver: macos-latest }
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@main # https://github.com/mamba-org/provision-with-micromamba
        with:
          environment-name: anaconda-client-env
          channels: conda-forge
          channel-priority: strict
          environment-file: conda/environment.yml
          extra-specs: |
            python=${{ matrix.pyver.distver }}
      - name: edit conda channel label if not on main
        if: github.ref != 'refs/heads/main'
        run: |
          echo "CONDALABEL=krande/label/dev" >> $GITHUB_ENV
          echo "CONDALABEL2= --label dev" >> $GITHUB_ENV
      - name: edit conda channel label if not on main
        if: github.ref != 'refs/heads/main'
        run: |
          echo "CONDALABEL=krande/label/dev" >> $GITHUB_ENV
          echo "CONDALABEL2= --label dev" >> $GITHUB_ENV
      - name: build
        run: |
          conda-build -c conda-forge -c ${{env.CONDALABEL}} . --python=${{ matrix.pyver.distver }} --user krande${{env.CONDALABEL2}} --token=${{ secrets.ANACONDA_TOKEN }}
        working-directory: conda


